### ISSUE TITLE
Remove vendor directory from source tree

### ISSUE THREAD

**Issue by bjohare** [TheRestartProject/restarters.net#114]
Since we're planning to move to a docker setup for development and deployment we don't need to hold the application dependencies in the source tree. We're aiming for a completely reproducible deployment regardless of the deployment environment. The docker setup includes a `composer install` step which makes it unnecessary to store dependencies in the repo. Storing the *vendor* directory also makes the repo unnecessarily large. See https://github.com/TheRestartProject/restarters.net/tree/dockerize

Removing the *vendor* directory is tricky however. The directory needs to be completely removed from git history, otherwise the repo size will not be reduced. Initial investigation suggests that using a tool like the [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) is probably the way to go. Once the repo is cleaned and updated, devs will need to checkout a clean copy so some coordination will be required. 

Not an urgent issue but logging here to capture comments.

**Comment by ngm** [comment]
+1, definitely want to get vendor out of the source tree.

Less concerned about it being in the history, but certainly if we can remove it without too much disruption, we should.

**Comment by ngm** [comment]
This is now the case - https://github.com/TheRestartProject/restarters.net/pull/390
