### ISSUE TITLE
Add redis caching to staging docker configuration

### ISSUE THREAD

**Issue by bjohare** [TheRestartProject/restarters.net#116]
We should be using redis for caching. This needs to be implemented first on staging in prep for eventual use in production. AFAIK production is using a file based cache at the moment.

**Comment by ngm** [comment]
Any there any resource overheads of using Redis?

We currently make pretty minimal use of caching (I think - at least active calls that we make, could be that Laravel does its own caching as well) so would like to weigh up pros and cons.

**Comment by bjohare** [comment]
Fair enough... I think the overheads are minimal but see https://redis.io/topics/faq for more info on this.
