### ISSUE TITLE
Tweaks to event photo upload notification email

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/restarters.net#121]
The email notification currently looks like this:

![image](https://user-images.githubusercontent.com/172324/61119599-1cb0b000-a493-11e9-8d21-bd473732f2e8.png)

We'd like to also add:

- extra event details: the date and start/end times of the event, and the group name
- if possible, thumbnails of the images that have been added, with a link that goes directly to the view the image (ideally to the event page with that image opened in the lightbox - but could just be a direct link to the uploaded image)
- the 'View event' button should go to the page to view the party, rather than the edit page

**Comment by spt1224** [comment]
Partially resolved in cde2302
