### ISSUE TITLE
API-key

### ISSUE THREAD

**Issue by monsieurhannes** [TheRestartProject/restarters.net#124]
Hi,
[We're a repair cafe in Sweden](https://therestartproject.org/groups/repair-cafe-malmo/) and we were wondering how it works to get an API key? I saw that there is an API for events and such, our plan is to get the event-data of our own events automatically from therestartproject.org and implement it on our homepage. Otherwise we have to create it over and over again...
I haven't seen any documentation about it, maybe I'm wrong, but it would be cool if someone could give me a hint :) 
Great project!

**Comment by ngm** [comment]
Hi @monsieurhannes - thanks!

We can set you up with an API key, would be great to have you help test it out.  

You'll need an account on https://restarters.net to have API access.  You could use one of the existing host accounts for Repair Cafe Malmö if you like.  The best thing would be to drop me and  James a private message in Talk (https://talk.restarters.net) and then we can work it out.

**Comment by ngm** [comment]
Closing as no response.
