### ISSUE TITLE
Large images do not persist when uploaded to event images

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/restarters.net#23]
As per here: https://talk.restarters.net/t/event-photos-not-saved-when-creating-an-event/526

**Comment by ngm** [comment]
We should either 

a) allow larger images
b) present a message saying this image is above the maximum size

**Comment by ngm** [comment]
@NikhitaPaturu - could you test this please and see if you can figure out what is causing the images to not upload sometimes.

It is possibly
- either the filesize is too large
- either the dimension is too large

**Comment by NikhitaPaturu** [comment]
I think the problem is with the limit of the filesize. 
* In php.ini - upload_max_filesize=750M(in my system)
