### ISSUE TITLE
In group dropdown field, extra space is been added 

### ISSUE THREAD

**Issue by NikhitaPaturu** [TheRestartProject/restarters.net#59]
Screenshot:
![capture](https://user-images.githubusercontent.com/18206485/49217317-26364d80-f3c5-11e8-9acf-5ca5ae1c6209.PNG)

**Comment by ngm** [comment]
Couple of suggestions:

- inspect the styling (in e.g. Chrome/Firefox dev tools) for the list elements, see if anything looks different in the CSS rules for those list items that are larger 
- see whether it is anything to do with the avatar images
