### ISSUE TITLE
When trying to edit(add description) a skill that has been created without description, then paragraph tags are added 

### ISSUE THREAD

**Issue by NikhitaPaturu** [TheRestartProject/restarters.net#61]
Screenshot:
![capture 1](https://user-images.githubusercontent.com/18206485/49217233-f38c5500-f3c4-11e8-8f68-ec2f5726915c.PNG)

**Comment by ngm** [comment]
Suggestions

- using summernote (the wysiwyg rich text editor) for editing skills description is unneccesary here (at least for now)
- remove the summernote from the description textarea when creating/editing a skill
