### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by NikhitaPaturu** [TheRestartProject/restarters.net#64]
* Following are the pages where footer is not sticking to bottom of the page:
     - /party/view/(id)
     - /skills
     - /tags
     - /category/edit/(id)
   - /search

**Comment by ngm** [comment]
Suggestions

- I think we will need to set a large min-height on the main container for any pages where this is happening

**Comment by NikhitaPaturu** [comment]
* Footer is missing on this page : /user/recovery page - this issue is moved to issue #72
