### ISSUE TITLE
In group search, name of group tag displays incorrectly

### ISSUE THREAD

**Issue by janetgunter** [TheRestartProject/restarters.net#77]
When as Admin, I go to Groups > All Groups > Search all groups [by tag]

I get "All restart groups" - when in this case it should read "All Refer groups" 

![screen shot 2018-09-10 at 13 53 03](https://user-images.githubusercontent.com/4210588/45299743-6c85ba00-b504-11e8-84cb-bbcaaad16328.png)

**Comment by ngm** [comment]
Closing old issues - the way group tag search is performed is different now, with no title above the search results, so this issue no longer occurs.

![image](https://user-images.githubusercontent.com/172324/134549659-b5dac90e-1729-49cf-81a2-b3096ba41eee.png)
