### ISSUE TITLE
Is summernote still stripping out formatting correctly?

### ISSUE THREAD

**Issue by ngm** [TheRestartProject/restarters.net#86]
see e.g.

https://therestartproject.org/parties/makespace-oxford/

The formatting has made it through, but it should have been removed when it was pasted in to the event.

**Comment by NikhitaPaturu** [comment]
* While creating or editing an event description, the format of the text is not changing.
Screenshot:
![capture1](https://user-images.githubusercontent.com/18206485/49800950-b61eb480-fd40-11e8-80e2-2f8c48551ff7.PNG)

* The event description text was ok on event view page.
Screenshot:
![capture2](https://user-images.githubusercontent.com/18206485/49801053-0433b800-fd41-11e8-966f-3870de08c6af.PNG)

* The text is not formatted on wordpress event description.
Screenshot:
![capture3](https://user-images.githubusercontent.com/18206485/49801098-2594a400-fd41-11e8-85f6-d2d6f5f44116.PNG)

**Comment by ngm** [comment]
We've switched to Quill.  https://github.com/TheRestartProject/restarters.net/pull/375
